#!/bin/bash

#©keithhedger Wed 11 Feb 15:18:13 GMT 2015 kdhedger68713@gmail.com


. /usr/share/LFSPkg/LFSFunctions

mkdir -vp /etc/gtk-2.0||true
mkdir -vp /etc/pango ||true
mkdir -vp /var/cache/man/fsstnd||true
mkdir -vp /usr/share/glib-2.0/||true

glib-compile-schemas /usr/share/glib-2.0/schemas

pango-querymodules > /etc/pango/pango.modules||true
gdk-pixbuf-query-loaders > /etc/gtk-2.0/gdk-pixbuf.loaders||true

gtk-query-immodules-2.0 --update-cache
gtk-update-icon-cache||true
gdk-pixbuf-query-loaders --update-cache

fc-cache -f||true

update-mime-database /usr/share/mime||true
mandb -c||true

exit 0
