#!/bin/bash

#©keithhedger Wed 18 Mar 20:13:22 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

GID=$(findnextgid "system")
groupadd -g $GID kvm||true

mkdir -vp /lib/udev/rules.d||true
cat > /lib/udev/rules.d/65-kvm.rules << "EOF"
KERNEL=="kvm", NAME="%k", GROUP="kvm", MODE="0660"
EOF

exit 0