#!/bin/bash -e

#©keithhedger Thu 19 Feb 12:04:16 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

mkdir -vp /usr/lib${LIBDIRSUFFIX}/pkgconfig

cat > /usr/lib${LIBDIRSUFFIX}/pkgconfig/xforms.pc<<EOF
prefix=/usr
libdir=/usr/lib${LIBDIRSUFFIX}
includedir=\${prefix}/include

Name: xforms
Description: GUI library
Version: ${VERSION}
Requires: 
Libs: -L\${libdir} -lforms
Cflags: -I\${includedir}
EOF

mkdir -vp /usr/share/applications
cat > /usr/share/applications/fdesign.desktop <<EOF
[Desktop Entry]
Name=Xforms Designer
Comment=
Terminal=false
Type=Application
Categories=Development;
Exec=fdesign
Icon=fdesign
EOF