#!/bin/bash -e

#©keithhedger Thu 19 Feb 13:05:33 GMT 2015 kdhedger68713@gmail.com

cat > /usr/share/applications/assistant-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Assistant 
Comment=Shows Qt5 documentation and examples
Exec=assistant
Icon=assistant-qt5.png
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Documentation;
EOF

cat > /usr/share/applications/designer-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Designer
GenericName=Interface Designer
Comment=Design GUIs for Qt5 applications
Exec=designer
Icon=designer-qt5.png
MimeType=application/x-designer;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF

cat > /usr/share/applications/linguist-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Linguist
Comment=Add translations to Qt5 applications
Exec=linguist
Icon=linguist-qt5.png
MimeType=text/vnd.trolltech.linguist;application/x-linguist;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF

cat > /usr/share/applications/qdbusviewer-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 QDbusViewer 
GenericName=D-Bus Debugger
Comment=Debug D-Bus applications
Exec=qdbusviewer
Icon=qdbusviewer-qt5.png
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Debugger;
EOF

cat > /etc/profile.d/qt5.sh << EOF
# Begin /etc/profile.d/qt5.sh

QT5DIR=/usr
export QT5DIR

# End /etc/profile.d/qt5.sh
EOF

export QT5LINK=/usr

if [ X"${QT5LINK}/lib" != "X$(grep -i "${QT5LINK}/lib" /etc/ld.so.conf)" ];then
	echo "${QT5LINK}/lib" >> /etc/ld.so.conf
	ldconfig||true
fi

mkdir -vp /etc/pango ||true
/usr/bin/gdk-pixbuf-query-loaders --update-cache||true
fc-cache -f||true
gtk-update-icon-cache --ignore-theme-index --force /usr/share/icons/hicolor||true
gtk-update-icon-cache --ignore-theme-index --force /usr/share/icons/gnome||true
/usr/bin/pango-querymodules > /etc/pango/pango.modules||true
update-mime-database /usr/share/mime||true
mkdir -vp /var/cache/man/fsstnd||true
mandb -c||true



