#!/bin/bash -e

#©keithhedger Thu 3 Dec 12:26:07 GMT 2015 kdhedger68713@gmail.com

cat > /etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

hosts: files dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF

cat > /etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf

/usr/lib64/qt5
/usr/lib/qt5

/usr/local/lib
/opt/lib

include /etc/ld.so.conf.d/*.conf
/usr/lib
EOF