#!/bin/bash
#©keithhedger Sun 22 Feb 16:50:36 GMT 2015

. /usr/share/LFSPkg/LFSFunctions

chmod 777 /tmp
mysql_install_db --basedir=/usr --datadir=/srv/mysql --user=mysql||true
chown -R mysql:mysql /srv/mysql

install -v -m755 -o mysql -g mysql -d /run/mysqld||true
mysqld_safe --user=mysql 2>&1 >/dev/null &

mysqladmin -u root password
mysqladmin -p shutdown

exit 0