#!/bin/bash -e

#©keithhedger Tue 3 Feb 12:04:53 GMT 2015 kdhedger68713@gmail.com

passwd root

sed -i 's@/lib/systemd/systemd-udevd@/lib/udev/udevd@' "/etc/rc.d/init.d/udev"
sed -i 's@/bin/udevadm@/sbin/udevadm@g' "/etc/rc.d/init.d/udev"
sed -i 's@/bin/udevadm@/sbin/udevadm@g' "/etc/rc.d/init.d/udev_retry"
sed -i 's@/lib/udev/udevd@/sbin/udevd@g' "/etc/rc.d/init.d/udev"
/sbin/udevadm hwdb --update
chmod +x /lib/udev/init-net-rules.sh
/lib/udev/init-net-rules.sh
/tools/bin/find /{,usr/}{bin,lib,sbin} -type f -exec /tools/bin/strip --strip-debug '{}' ';'


