#!/bin/bash -e

#©keithhedger Wed 4 Feb 13:38:52 GMT 2015 kdhedger68713@gmail.com

mkdir -vp /etc/modprobe.d||true
cat > /etc/modprobe.d/usb.conf << "EOF"
# Begin /etc/modprobe.d/usb.conf

install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

# End /etc/modprobe.d/usb.conf
EOF
