#!/bin/bash

#©keithhedger Fri 13 Feb 12:10:33 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

UIDGIDPAIR=$(findnextpair "system")
useradd -c "Network Time Protocol" -d /var/lib/ntp -ru $UIDGIDPAIR -s /bin/false ntp||true

cat > /etc/ntp.conf << "EOF"
server 0.uk.pool.ntp.org
server 1.uk.pool.ntp.org
server 2.uk.pool.ntp.org
server 3.uk.pool.ntp.org

driftfile /etc/ntp/drift
restrict 127.0.0.1

pidfile   /var/run/ntpd.pid

EOF

exit 0