#!/bin/bash -e

#©keithhedger Thu 12 Feb 16:09:33 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

mkdir -vp /usr/lib${LIBDIRSUFFIX}/gimp/2.0/plug-ins||true

ln -v -s /usr/bin/xsane /usr/lib${LIBDIRSUFFIX}/gimp/2.0/plug-ins/||true
ln -v -s firefox /usr/bin/netscape||true
