#!/bin/bash -e

#©keithhedger Mon 16 Feb 13:24:43 GMT 2015 kdhedger68713@gmail.com

cat > /usr/share/applications/thunderbird.desktop << EOF
[Desktop Entry]
Encoding=UTF-8
Name=Thunderbird Mail
Comment=Send and receive mail with Thunderbird
GenericName=Mail Client
Exec=thunderbird %u
Terminal=false
Type=Application
Icon=thunderbird
Categories=Application;Network;Email;
MimeType=application/xhtml+xml;text/xml;application/xhtml+xml;application/xml;application/rss+xml;x-scheme-handler/mailto;
StartupNotify=true
EOF
