#!/bin/bash -e

#©keithhedger Mon 2 Feb 13:04:50 GMT 2015 kdhedger68713@gmail.com

if [ -e ./SystemData ];then
	. ./SystemData
else
	echo "No SystemData file found ..."
	exit 1
fi

echo "LFS location:" $LFS
echo "LFS version:" $LFSVERSION
echo "LFS Hostname:" $LFSNAME
echo "Kernel version:" $KERNELVERSION
echo "INIT type:" $INITTYPE
echo
echo "Folder for downloaded source archives:" $SOURCEARCHIVES
echo "Folder for built packages:" $BUILTPACKAGES
echo
echo "LFS language:" $LANGUAGE
echo "Raw LFS  device:" $ROOTDEV
echo "LFS filesystem type:" $ROOTFSTYPE
echo "Swap partition:" $SWAP
echo "Suffix for LFS lib folders ( eg /usr/lib${LIBDIRSUFFIX} ):" $LIBDIRSUFFIX
echo
echo "LFS IP address:" $IP
echo "LFS gateway:" $GATEWAY
echo "LFS subnet:" $SUBNET
echo "LFS name server list:" $NAMESERVERS
echo "LFS keyboard:" $KEYBOARD

