#!/bin/bash
#©keithhedger Thu 19 Mar 11:46:53 GMT 2015

. /usr/share/LFSPkg/LFSFunctions

cat >> ${JAVA_HOME}/jre/lib/sound.properties << "EOF"
# Begin PulseAudio provider additions:

javax.sound.sampled.Clip=org.classpath.icedtea.pulseaudio.PulseAudioClip
javax.sound.sampled.SourceDataLine=org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine
javax.sound.sampled.TargetDataLine=org.classpath.icedtea.pulseaudio.PulseAudioTargetDataLine

# End PulseAudio provider additions
EOF
